apiVersion: v1
kind: Service
metadata:
  name: trendpredict-ui-service
  namespace: trendpredict
  labels:
    app: trendpredict-ui
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: trendpredict-ui
  type: LoadBalancer
